package net.codejava.mysql.model;
// Generated 2020-3-22 12:23:38 by Hibernate Tools 5.2.12.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * News generated by hbm2java
 */
@Entity
@Table(name = "news", catalog = "db_hibernate_demo", uniqueConstraints = @UniqueConstraint(columnNames = "TITLE"))
public class News implements java.io.Serializable {

	private Integer id;
	private String title;
	private String author;
	private Date date;
	private String content;
	private byte[] image;

	public News() {
	}

	public News(String title, String author, Date date, String content, byte[] image) {
		this.title = title;
		this.author = author;
		this.date = date;
		this.content = content;
		this.image = image;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "TITLE", unique = true, length = 20)
	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	@Column(name = "AUTHOR", length = 20)
	public String getAuthor() {
		return this.author;
	}

	public void setAuthor(String author) {
		this.author = author;
	}

	@Temporal(TemporalType.TIME)
	@Column(name = "DATE", length = 8)
	public Date getDate() {
		return this.date;
	}

	public void setDate(Date date) {
		this.date = date;
	}

	@Column(name = "CONTENT", length = 16777215)
	public String getContent() {
		return this.content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	@Column(name = "IMAGE")
	public byte[] getImage() {
		return this.image;
	}

	public void setImage(byte[] image) {
		this.image = image;
	}

}
