package net.codejava.mysql.model;
// Generated 2020-3-22 12:23:38 by Hibernate Tools 5.2.12.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Worker generated by hbm2java
 */
@Entity
@Table(name = "worker", catalog = "db_hibernate_demo")
public class Worker implements java.io.Serializable {

	private Integer id;
	private String name;
	private Integer monthlyPay;
	private Integer yearlyPay;
	private Integer vocationWithPay;

	public Worker() {
	}

	public Worker(String name, Integer monthlyPay, Integer yearlyPay, Integer vocationWithPay) {
		this.name = name;
		this.monthlyPay = monthlyPay;
		this.yearlyPay = yearlyPay;
		this.vocationWithPay = vocationWithPay;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "ID", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "NAME")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "MONTHLY_PAY")
	public Integer getMonthlyPay() {
		return this.monthlyPay;
	}

	public void setMonthlyPay(Integer monthlyPay) {
		this.monthlyPay = monthlyPay;
	}

	@Column(name = "YEARLY_PAY")
	public Integer getYearlyPay() {
		return this.yearlyPay;
	}

	public void setYearlyPay(Integer yearlyPay) {
		this.yearlyPay = yearlyPay;
	}

	@Column(name = "VOCATION_WITH_PAY")
	public Integer getVocationWithPay() {
		return this.vocationWithPay;
	}

	public void setVocationWithPay(Integer vocationWithPay) {
		this.vocationWithPay = vocationWithPay;
	}

}
