package net.codejava.oracle.model;
// Generated 2020-3-22 21:34:37 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Bonus generated by hbm2java
 */
@Entity
@Table(name = "BONUS", schema = "SCOTT")
public class Bonus implements java.io.Serializable {

	private BonusId id;

	public Bonus() {
	}

	public Bonus(BonusId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "ename", column = @Column(name = "ENAME", length = 10)),
			@AttributeOverride(name = "job", column = @Column(name = "JOB", length = 9)),
			@AttributeOverride(name = "sal", column = @Column(name = "SAL", precision = 22, scale = 0)),
			@AttributeOverride(name = "comm", column = @Column(name = "COMM", precision = 22, scale = 0)) })
	public BonusId getId() {
		return this.id;
	}

	public void setId(BonusId id) {
		this.id = id;
	}

}
