package net.codejava.oracle.model;
// Generated 2020-3-22 21:34:37 by Hibernate Tools 5.2.12.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Salgrade generated by hbm2java
 */
@Entity
@Table(name = "SALGRADE", schema = "SCOTT")
public class Salgrade implements java.io.Serializable {

	private SalgradeId id;

	public Salgrade() {
	}

	public Salgrade(SalgradeId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "grade", column = @Column(name = "GRADE", precision = 22, scale = 0)),
			@AttributeOverride(name = "losal", column = @Column(name = "LOSAL", precision = 22, scale = 0)),
			@AttributeOverride(name = "hisal", column = @Column(name = "HISAL", precision = 22, scale = 0)) })
	public SalgradeId getId() {
		return this.id;
	}

	public void setId(SalgradeId id) {
		this.id = id;
	}

}
